#!/bin/sh

uci -q batch <<-EOF >/dev/null 2>&1
	delete ucitrack.@AdGuardHome2[-1]
	add ucitrack AdGuardHome2
	set ucitrack.@AdGuardHome2[-1].init=AdGuardHome2
	commit ucitrack
	delete AdGuardHome2.AdGuardHome2.ucitracktest
EOF

rm -f /tmp/luci-indexcache
chmod +x /etc/init.d/AdGuardHome2 /usr/share/AdGuardHome2/*
exit 0
